# Generated by Django 3.2.2 on 2021-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_datetime',
            new_name='create_datetime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_author_rating',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_create_datetime',
            new_name='create_datetime',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=128),
        ),
    ]
