# Generated by Django 3.2.2 on 2021-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210521_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='authors_rating',
        ),
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.SmallIntegerField(default=1),
        ),
    ]
