# Generated by Django 3.2.2 on 2021-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210521_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
